---
name: Clojure Snyk Check

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

jobs:
 snyk_scan:
   runs-on: ubuntu-latest
   if: contains(github.event.pull_request.labels.*.name, 'safe to test')
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@main
      with:
        snykToken: ${{ secrets.SNYK_PE_TOKEN }}
        rproxyKey: ${{ secrets.SEC_PUBLIC_RPROXY_KEY }}
        snykOrg: 'puppet-enterprise'
        snykProject: 'jruby-utils'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
